Master
DyllanRuth/software-product-sprint-or-my-portfolio pull request #2
Opened 2021-03-02 00:31 UTC by DyllanRuth

2021-03-02 05:24 UTC, kboni-tc requested changes
Wowowowow!!! Awesome work and first PR, Dyllan! Mainly some minor nitpicks and style suggestions.

2021-03-02 05:24 UTC, kboni-tc commented on portfolio/src/main/webapp/index.html
> +
Newline can be removed here, same throughout. See https://google.github.io/styleguide/htmlcssguide.html#General_Formatting for general formatting recommendations.

2021-03-02 05:24 UTC, kboni-tc commented on portfolio/src/main/webapp/index.html
> +        <header><div class="logo">
From Google HTML/CSS style guide "Indent by 2 spaces at a time," same throughout. See https://google.github.io/styleguide/htmlcssguide.html#Indentation.

2021-03-02 05:24 UTC, kboni-tc commented on portfolio/src/main/webapp/index.html
> +<head>
(Optional) Certain optional tags, like `<head>` can be removed, for more details see https://google.github.io/styleguide/htmlcssguide.html#Optional_Tags.

2021-03-02 05:24 UTC, kboni-tc commented on portfolio/src/main/webapp/Js/index.js
> +const navToggle = document.querySelector('.nav-toggle');
Did this file get duplicated from webapp/index.js?

2021-03-02 05:24 UTC, kboni-tc commented on portfolio/src/main/webapp/index.js
> +const navToggle = document.querySelector('.nav-toggle');
Declare variables right before they are used.
From Google JavaScript style guide " local variables are declared close to the point they are first used (within reason), to minimize their scope, https://google.github.io/styleguide/jsguide.html#features-declared-when-needed.

2021-03-02 05:24 UTC, kboni-tc commented on portfolio/src/main/webapp/index.js
> +navLinks.forEach(link => {
Optional: prefer a for-of loop. From https://google.github.io/styleguide/jsguide.html#features-for-loops, "With ES6, the language now has three different kinds of for loops. All may be used, though for-of loops should be preferred when possible."

2021-03-02 05:24 UTC, kboni-tc commented on portfolio/src/main/webapp/portfolio-item.html
> +
Remove newline here.

2021-03-02 05:24 UTC, kboni-tc commented on portfolio/src/main/webapp/style.css
> +{
Move opening brace to he same line as the last selector in a given rule with a space between the last selector and opening brace, same throughout, see:
https://google.github.io/styleguide/htmlcssguide.html#Declaration_Block_Separation

2021-03-02 05:24 UTC, kboni-tc commented on portfolio/src/main/webapp/style.css
> +        "title img"
Use single ('') rather than double ("") quotation marks for attribute selectors and property values, see https://google.github.io/styleguide/htmlcssguide.html#CSS_Quotation_Marks.

2021-03-02 05:24 UTC, kboni-tc commented on portfolio/src/main/webapp/style.css
> +*,
Optional: Maybe group sections by section comments? See https://google.github.io/styleguide/htmlcssguide.html#Section_Comments.

2021-03-02 05:24 UTC, kboni-tc commented on portfolio/src/main/webapp/style.css
> +    background: var(--clr-light);
Indentation should be by 2 spaces at a time. Same throughout file.

2021-03-02 05:24 UTC, kboni-tc commented on portfolio/src/main/webapp/index.html
> +        <img src="img/IMG_48952.jpg" alt="My picture ok" class="intro__img">
nitpick: change image file name to something more meaningful.

2021-03-05 20:41 UTC, closed without merging

2021-03-05 20:41 UTC, DyllanRuth commented
Thank you! I have fixed the errors